sudo: required
services:
- docker
language: bash
script:
- |
  echo "Updating Docker to have docker manifest command"
  curl https://get.docker.com | sh
  echo "Enabling docker client experimental features"
  mkdir -p ~/.docker
  echo '{ "experimental": "enabled" }' > ~/.docker/config.json
  docker version
# prepare qemu
- docker run --rm --privileged multiarch/qemu-user-static:register --reset
# build image
- docker build --build-arg distro=wheezy -t rpi-mysql .
# test image
- docker run rpi-mysql mysql --version
# push image
- >
  if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
    docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
    TAG=$(grep "ENV MYSQL_VERSION" Dockerfile | awk 'NF>1{print $NF}')
    docker tag rpi-mysql adamburns/rpi-mysql:arm-$TAG
    docker push adamburns/rpi-mysql:arm-$TAG
    docker manifest create adamburns/rpi-mysql:$TAG adamburns/rpi-mysql:arm-$TAG
    docker manifest annotate adamburns/rpi-mysql:$TAG adamburns/rpi-mysql:arm-$TAG --os linux --arch arm --variant v6
    docker manifest push adamburns/rpi-mysql:$TAG
    docker manifest create adamburns/rpi-mysql adamburns/rpi-mysql:arm-$TAG
    docker manifest annotate adamburns/rpi-mysql adamburns/rpi-mysql:arm-$TAG --os linux --arch arm --variant v6
    docker manifest push adamburns/rpi-mysql
  fi
